# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        main:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

          # -> custom firewall for the admin area of the URL
        admin:
            pattern:            /fp_admin(.*)
            context:            user
            form_login:
                provider:       main
                login_path:     /fp_admin/login
                use_forward:    false
                check_path:     /fp_admin/login_check
                failure_path:   null
            logout:
                path:           /fp_admin/logout
                target:         /fp_admin/login
            anonymous:          true

        main:
#            anonymous: ~
            pattern:      ^/
            anonymous:    true
            provider:     main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     fos_user_security_login
                handlers:   [pgde_emploi.logout_listener]
            remember_me:
                secret:     %secret%
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented

    encoders:
        Pgde\EmploiBundle\Entity\Utilisateur: sha512

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Admin login page needs to be accessed without credential
        - { path: ^/fp_admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fp_admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fp_admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fp_admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/fp_admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

