<?php

namespace Pgde\EmploiBundle\Repository;

/**
 * AcademicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademicRepository extends \Doctrine\ORM\EntityRepository
{
}
