<?php

namespace Pgde\EmploiBundle\Repository;

/**
 * CategorieHandicapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieHandicapRepository extends \Doctrine\ORM\EntityRepository
{
}
