<?php

namespace Pgde\EmploiBundle\Repository;

/**
 * HandicapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HandicapRepository extends \Doctrine\ORM\EntityRepository
{
}
