<?php

namespace Pgde\EmploiBundle\Repository;

/**
 * UserdataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserdataRepository extends \Doctrine\ORM\EntityRepository
{
}
