pgde_emploi_userdata:
    resource: "@PgdeEmploiBundle/Resources/config/routing/userdata.yml"
    prefix:   /

pgde_emploi_homepage:
    path:     /empl
    defaults: { _controller: PgdeEmploiBundle:Default:index }
